### ISSUE TITLE
fix to center 3 logs on "Supporting by"

### ISSUE THREAD

**Issue by atsubo5735** [evolableasia/hackathon#1]
please fix the center on 3 logs

I'm up on sample screen
<img width="1256" alt="2018-02-28 15 18 45" src="https://user-images.githubusercontent.com/14917757/36777115-ccfb83fe-1c9a-11e8-94dd-da549e9f6c0e.png">

**Comment by hangttt2** [comment]
@atsubo5735 
Mr.Thinh confirmed this issue. 
I fixed it already.
I'll share you the link to testing later.
